
import Header from "./components/Header";
import Footer from "./components/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <main className=" w-screen min-h-screen flex flex-col items-center justify-between">
        <Header />
        {children}
        <Footer />
    </main>
  );
}
